version: '2'
services:
  api:
    image: narzhan/domain-analyzer:1.2
    stdin_open: true
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "1"
    network_mode: host
    environment:
      CELERY_BROKER: "redis://localhost:6379/3"
      MODE: "api"
      CACHE_RESULTS: "localhost"
      CACHE_ANALYSIS: "localhost"
      RESULTS_DB: "2"
      ANALYSIS_DB: "4"
    tty: true
  domain_analyzer:
    image: narzhan/domain-analyzer:1.2
    environment:
        CELERY_BROKER: "redis://localhost:6379/3"
        MODE: "domain_analyzer"
        CACHE_RESULTS: "localhost"
        CACHE_ANALYSIS: "localhost"
        RESULTS_DB: "2"
        ANALYSIS_DB: "4"
        RECORD_TTL: "680400"
        BING_API_KEY: ""
        PERSIST_DATA: "true"
        KERAS_BACKEND: "theano"
        TEST_MODE: "true"
    stdin_open: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "1"
    tty: true
    volumes:
      - /opt/domain_analyzer/logs/:/opt/domain_analyzer/logs/
      - /opt/domain_analyzer/data/:/opt/domain_analyzer/data/
  redis:
    image: redis:5.0
    network_mode: host